import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { PrimaryButton } from "./components/PrimaryButton";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>テスト</h1>
        <PrimaryButton />
        <Link href="/ssr">
          <a>SSR</a>
        </Link>
        <Link href="/ssg">
          <a>SSG</a>
        </Link>
        <Link href="/isr">
          <a>ISR</a>
        </Link>
      </main>
    </div>
  );
}
